### ISSUE TITLE
no module named gdal

### ISSUE THREAD

**Issue by BenjiDa** [LSDtopotools/lsdtt_notebooks#2]
I followed the instructions running LSDTT using docker, installing python packages with `# install_lsdtt_python_packages.sh`, running jupyter notebook. But when I try to import modules, e.g., `import lsdviztools.lsdbasemaptools as bmt` it fails to load gdal.  Not sure if this is a new problem with the docker container or something on my end, I previously got this container to work in February.  Full error message below

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_54/1438262229.py in <module>
----> 1 import lsdviztools.lsdbasemaptools as bmt
      2 from lsdviztools.lsdplottingtools import lsdmap_gdalio as gio
      3 import lsdviztools.lsdmapwrappers as lsdmw
      4 import lsdttparamselector as ps

/usr/local/lib/python3.8/site-packages/lsdviztools/lsdbasemaptools/__init__.py in <module>
      7 from __future__ import absolute_import, division, print_function
      8 
----> 9 from .lsdmap_basemaptools import *
     10 from .lsdmap_otgrabber import *

/usr/local/lib/python3.8/site-packages/lsdviztools/lsdbasemaptools/lsdmap_basemaptools.py in <module>
     21 import cartopy.io.shapereader as shpreader
     22 
---> 23 from lsdviztools.lsdplottingtools import lsdmap_gdalio as LSDMGDAL
     24 #from lsdplottingtools import lsdmap_gdalio as LSDMGDAL
     25 #from mpl_toolkits.basemap import Basemap

/usr/local/lib/python3.8/site-packages/lsdviztools/lsdplottingtools/__init__.py in <module>
     12 from .lsdmap_basicmanipulation import *
     13 from .lsdmap_pointtools import *
---> 14 from .lsdmap_chiplotting import *
     15 from .lsdmap_saplotting import *
     16 from .lsdmap_subplots import *

/usr/local/lib/python3.8/site-packages/lsdviztools/lsdplottingtools/lsdmap_chiplotting.py in <module>
     28 from lsdviztools.lsdplottingtools import init_plotting_DV
     29 from lsdviztools.lsdplottingtools import adjust_text
---> 30 from lsdviztools.lsdplottingtools import lsdmap_vectortools as LSDP
     31 from lsdviztools.lsdplottingtools import lsdmap_pointtools as PointTools
     32 from lsdviztools.lsdmapfigure import plottinghelpers as Helper

/usr/local/lib/python3.8/site-packages/lsdviztools/lsdplottingtools/lsdmap_vectortools.py in <module>
     15 from osgeo import ogr, osr
     16 from lsdviztools import lsdplottingtools as LSDPT
---> 17 import gdal as gdal
     18 from osgeo.gdalconst import GA_ReadOnly
     19 from lsdviztools.lsdmapfigure import plottinghelpers as Helper

ModuleNotFoundError: No module named 'gdal'`

**Comment by simon-m-mudd** [comment]
Hi Ben, 
I need to update the container, but you can get this working for now with:
pip install lsdviztools --upgrade

(you can test with)

import lsdviztools
lsdviztools.__version__


the gdal bug has been fixed in lsdviztools 0.4.6

**Comment by simon-m-mudd** [comment]
Note: the install script is redundant (I will delete from the repo shortly). 

lsdtt command line tools (that is, all the c++), lsdviztools and lsdtopytools are pre-installed on the container
