### ISSUE TITLE
'my_OT_api_key.txt' file location

### ISSUE THREAD

**Issue by DaisyUoE** [LSDtopotools/lsdtt_notebooks#3]
Hi Simon, I am running the river network code in Google Colab for my study area. I have obtained my OpenTopography API Key and have saved it into a file named 'my_OT_api_key.txt'. Could you please advise on where I should place this file? I got an error message saying the code cannot locate and read the file during execution. Thanks. -Daisy

**Comment by simon-m-mudd** [comment]
Hi Daisy, I know you have already solved this but for completeness the "my_OT_api_key.txt" just goes in your working directory. So the same place you are putting the data.
